//WARNING: This code was auto generated by template compiler, do not modify by hand!
//Generated on 14.06.2015 9:43:39 by NFX.Templatization.TextCSTemplateCompiler at TRIAL

using System; 
using System.Text; 
using System.Linq; 
using System.Collections.Generic; 

namespace WavePerformanceComparison.Pages 
{

 ///<summary>
 /// JSON echo test page
 ///</summary>
 public  class EchoJson : WavePerformanceComparison.Pages.Master
 {

     protected override void DoRender()
     {
       base.DoRender();
        Target.Write( EchoJson._17_S_LITERAL_0 );

     }
    protected override void  renderBody()
    {
        Target.Write( EchoJson._17_S_LITERAL_1 );

    }


     #region Literal blocks content
        private const string _17_S_LITERAL_0 = @"

    
"; 
        private const string _17_S_LITERAL_1 = @"
    <h2>Fill data and submit the form to run the JSON echo test:</h2>
    <form id=""frm"" action=""/mvc/test/echojson"" method=""post"">
        First name: <input type=""text"" name=""firstname""><br>
        Last name:  <input type=""text"" name=""lastname"">
        <input type=""submit"" value=""Submit"">
    </form>"; 
     #endregion

 }//class
}//namespace
