//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavePerformanceComparison.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WavePerformanceComparison.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadya
        ///Aahana
        ///Aalayah
        ///Aaleyah
        ///Aaliah
        ///Aaliya
        ///Aaliyah
        ///Aaliyha
        ///Aalyah
        ///Aalyiah
        ///Aaniyah
        ///Aanya
        ///Aaralyn
        ///Aarna
        ///Aaron
        ///Aarushi
        ///Aarya
        ///Aaryn
        ///Aashi
        ///Aashna
        ///Abagail
        ///Abbagail
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abbigail
        ///Abbigale
        ///Abbigayle
        ///Abby
        ///Abbygail
        ///Abbygale
        ///Abcde
        ///Abella
        ///Abigael
        ///Abigail
        ///Abigale
        ///Abigayle
        ///Abilene
        ///Abree
        ///Abriana
        ///Abrianna
        ///Abriella
        ///Abrielle
        ///Abril
        ///Abygail
        ///Acacia
        ///Acadia
        ///Acelynn
        ///Ada
        ///Adah
        ///Adalee
        ///Adaleigh
        ///Adalia
        ///Adalie
        ///Adalina
        ///Adaline
        ///Adalyn
        ///Adalynn
        ///Adalynne
        ///Adamari
        ///Adamaris [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Femalenames {
            get {
                return ResourceManager.GetString("Femalenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbott
        ///Abernathy
        ///Adair
        ///Adams
        ///Adkins
        ///Aguirre
        ///Alexander
        ///Allen
        ///Allen
        ///Allison
        ///Almeida
        ///Alvarado
        ///Alvarez
        ///Andersen
        ///Anderson
        ///Anderson
        ///Andrews
        ///Archer
        ///Armstrong
        ///Arnold
        ///Arsenault
        ///Ashby
        ///Ashworth
        ///Atkinson
        ///Austin
        ///Ayers
        ///Bailey
        ///Bailey
        ///Bain
        ///Baird
        ///Baker
        ///Baldwin
        ///Ball
        ///Ballard
        ///Banks
        ///Barker
        ///Barnes
        ///Barnett
        ///Barr
        ///Barrett
        ///Barry
        ///Bartlett
        ///Barton
        ///Batchelor
        ///Bateman
        ///Bates
        ///Bauer
        ///Baxter
        ///Beach
        ///Beasley
        ///Beck
        ///Beebe
        ///Bell
        ///Bender
        ///Bennett
        ///Bennett
        ///Benson
        ///Bentley
        ///Benton
        ///Berry
        ///Bird
        ///Bishop
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lastnames {
            get {
                return ResourceManager.GetString("Lastnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadan
        ///Aaden
        ///Aadi
        ///Aadin
        ///Aaditya
        ///Aadon
        ///Aadyn
        ///Aahan
        ///Aahil
        ///Aaiden
        ///Aakash
        ///Aamir
        ///Aarav
        ///Aaren
        ///Aaric
        ///Aarin
        ///Aariz
        ///Aarnav
        ///Aaron
        ///Aarush
        ///Aarya
        ///Aaryan
        ///Aaryn
        ///Aasim
        ///Aayan
        ///Aayden
        ///Aayush
        ///Abbas
        ///Abbott
        ///Abdallah
        ///Abdelrahman
        ///Abdi
        ///Abdias
        ///Abdiel
        ///Abdirahman
        ///Abdoul
        ///Abdoulaye
        ///Abdul
        ///Abdulahi
        ///Abdulaziz
        ///Abdullah
        ///Abdullahi
        ///Abdulmalik
        ///Abdulrahman
        ///Abdurrahman
        ///Abe
        ///Abel
        ///Abelardo
        ///Abhay
        ///Abhinav
        ///Abhiram
        ///Abhishek
        ///Abiel
        ///Abimael
        ///Abisai
        ///Able
        ///Abner
        ///Abraham
        ///Abrahan
        ///Abrahm
        ///Abram
        ///Abran
        ///Abub [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Malenames {
            get {
                return ResourceManager.GetString("Malenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Able Seamen
        ///Account Collector
        ///Accounting Specialist
        ///Adjustment Clerk
        ///Administrative Assistant
        ///Administrative Law Judge
        ///Administrative Service Manager
        ///Admiralty Lawyer
        ///Adult Literacy and Remedial Education Teachers
        ///Advertising Account Executive
        ///Advertising Agency Coordinator
        ///Aeronautical &amp; Aerospace Engineer
        ///Aerospace Engineering Technician
        ///Agricultural Crop Farm Manager
        ///Agricultural Engineer
        ///Agricultural Equipment Operator
        ///Agricultural Inspector
        ///Agricultural Product Sorter
        ///Agricultural Sci [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Occupations {
            get {
                return ResourceManager.GetString("Occupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///University of Aberdeen
        ///Abertay University
        ///Aberystwyth University
        ///Anglia Ruskin University, Cambridge
        ///The Arts University Bournemouth
        ///University of the Arts London
        ///Camberwell College of Arts
        ///Central Saint Martins College of Art and Design
        ///Chelsea College of Art and Design
        ///London College of Communication
        ///London College of Fashion
        ///Wimbledon College of Art
        ///Aston University, Birmingham
        ///Bangor University
        ///University of Bath
        ///Bath Spa University
        ///University of Bedfordshire, Luton and Bedford
        ///Univer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Universities {
            get {
                return ResourceManager.GetString("Universities", resourceCulture);
            }
        }
    }
}
